FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ui/ ui/
COPY src/ src/
COPY data/image_stats.csv data/image_stats.csv

EXPOSE 8501
ENV API_URL=http://api:8000
CMD ["streamlit", "run", "ui/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
